/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 chair.gltf --transform
Author: CzernO (https://sketchfab.com/czernobog)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cherries-23754527234540959add0b2592876de0
Title: Cherries
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cherries-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.defaultMat_7} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.defaultMat_6} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.defaultMat_5} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.defaultMat_4} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.defaultMat_3} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.defaultMat_3} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.defaultMat_3} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.defaultMat_3} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.defaultMat_2} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.defaultMat_2} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.defaultMat_1} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.defaultMat_1} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.defaultMat_0} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.defaultMat_0} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.defaultMat} />
      </group>
    </group>
  )
}

useGLTF.preload('/cherries-transformed.glb')
